### ISSUE TITLE
Nodemanager Questions

### ISSUE THREAD

**Issue by janiemort** [oracle/fmw-chef-cookbook#10]
Hi,

I'm using the cookbooks to build a WebLogic 10.3.6 domain with an Admin Server and one managed server that runs on a remote VM. 

I have not been able to figure out how to build the Nodemanagers on each VM with names that match the names (i.e., nodemanager id) in the array of nodemanagers that I have configured.  The Nodemanager recipe seems to name the nodemanager LocalMachine rather than what I have specified in the array.  Here is my example from my attributes/default.rb:

```
default['fmw_domain']['nodemanager_listen_address'] = node['ipaddress']
default['fmw_domain']['nodemanagers'] =
  [
    {
      'id' => '1pldrdgfas01',
      'listen_address' => '172.28.128.4'
    }
  ]


default['fmw_domain']['servers'] =
  [
    {
      'id' => 'ecomws_server01',
      'nodemanager' => '1pldrdgfas01'
      'listen_address' => '172.28.128.4',
      'listen_port' => 8010,
      'arguments' => '-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m'
    }
  ]
```

How can I override the nodemanager name so that it matches what I'm using to assign to my servers? If I don't include the Nodemanager recipe, I get no nodemanager configuration at all. 

Thanks!

Jane

**Comment by janiemort** [comment]
Oops, there is a comma missing at the end of this line:

'nodemanager' => '1pldrdgfas01'

**Comment by janiemort** [comment]
I downloaded the samples and went through the recipes and attributes and can see that LocalMachine is hard-coded. It also isn't possible to override the assignment of the Admin Server to the LocalMachine. 

It sounds like the only solution is to write my own Nodemanager recipe that will allow me to register it as a service, create the machine with a name other than LocalMachine, and assign AdminServer to the correct machine. It does appear that the Nodemanager configuration in the domain.py is working okay. 

Are there any plans to provide a more complete set of nodemanager recipes to handle remote managed servers?

Thanks!

Jane

**Comment by biemond** [comment]
Hi,

Indeed LocalMachine is hard coded for the AdminServer see
https://github.com/oracle/chef-samples/blob/master/fmw_domain/templates/default/domain/domain.py#L20

and I did this because some of the SOA 11g domain extension are also using this machine name and I cannot get rid of it.
There is no tight connection between WLS machine name and the real vm hostname, if wls can reach the ip of this machine it will be ok. So localMachine should not be a problem. For other managed servers and nodemanagers/machines you will be in control.

But basically we don't support multi VM yet but it doesn't mean you cannot do it and probably only have to do some manual tasks.

I can see nodemanager for 11g requires the domain recipe so we cannot use it on the other VM's This should be optional for 11g. 

So on the second VM , do your normal install and patching.  if your are using 11g you can copy the nodemanager recipe to your  cookbook and remove the domain dependency. This will also create the nodemanager service.

Copy the domain on the first VM (pack) on the 2nd VM do an unpack.  for 12c You can start the nodemanager from the domain bin folder . Or after unpack you can add the domain and nodemanager recipe to wls install/patch, chef will detect the current state.

For 11g you have to do an nmenroll so the nodemanager is authorized/ connected to the domain.

And start the server on VM two from the wls console.

So this code will create a 2nd machine beside the LocalMachine for the AdminServer.  Plus a managed servers which is connected to the node2 machine.

```
    "nodemanagers": [
      {
        "id": "node2",
        "listen_address": "192.168.2.200"
      }
    ],
    "servers": [
      {
        "id": "server2",
        "nodemanager": "node2",
        "listen_address": "192.168.2.200",
        "listen_port": 8001,
        "arguments": "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m"
      }
    ],

```

Hope this helps

**Comment by janiemort** [comment]
Yes that helps. It confirms what I thought. We like to name our weblogic machines after the hostname so that we can easily identify it in the weblogic console. That is the only reason for wanting to customize the name. 

Thanks very much for your help.

**Comment by biemond** [comment]
yeah, 

we can add a machine parameter to the domain recipe with LocalMachine as default value and pass that on to the domain script. 

For vanilla wls this will work, for soa 11g etc this can be overriden by the domain extension template

thanks

**Comment by scarolan** [comment]
Hi @biemond - Sean here.  I'm working with Jane to implement your cookbooks to install Weblogic.  I had a quick question - is there a reason or design decision to put the IP address and port that weblogic runs on into the data bag?  These might be more manageable if they were simple node attributes...

**Comment by biemond** [comment]
Hi,

I did this for future changes, I want to share domain information through a databag to the cluster nodes. So I have all the information I need for these wls nodes.

Thanks
